import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { renderProposalHtml } from '@/lib/proposal-html'
import type { Proposal, ProposalItem } from '@/types'

/**
 * The client's own view of a proposal: /admin/p/<token>.
 *
 * The token is 48 hex characters generated by the database, and it is the
 * only credential: anyone holding the link can read the proposal and approve
 * it, exactly as they could with a PDF in their inbox. Nothing here reveals
 * another client's data, and the route never accepts an id.
 *
 * GET renders the page (and records the first view). POST is the approve /
 * decline form, and redirects back to GET so a refresh cannot double-submit.
 */

const TOKEN_RE = /^[0-9a-f]{48}$/

async function load(token: string) {
  const supabase = createAdminClient()
  const { data: proposal } = await supabase
    .from('proposals')
    .select('*, contact:contacts(id, first_name, last_name, email, phone, company:companies(name)), company:companies(id, name)')
    .eq('public_token', token)
    .maybeSingle()
  if (!proposal) return null
  const { data: items } = await supabase
    .from('proposal_items')
    .select('*')
    .eq('proposal_id', proposal.id)
    .order('sort_order')
  return { supabase, proposal: proposal as Proposal, items: (items ?? []) as ProposalItem[] }
}

function notFound() {
  return new Response(
    `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Not found</title><style>body{font-family:system-ui,sans-serif;max-width:32rem;margin:6rem auto;padding:0 1.5rem;color:#22222a;line-height:1.6}a{color:#B8860B}</style></head><body><h1>We cannot find that proposal</h1><p>The link may have been mistyped, or the proposal may have been withdrawn. Email <a href="mailto:Hello@occasionsbox.com">Hello@occasionsbox.com</a> and we will send you a fresh one.</p></body></html>`,
    { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8', 'X-Robots-Tag': 'noindex, nofollow' } }
  )
}

export async function GET(_request: Request, { params }: { params: Promise<{ token: string }> }) {
  const { token } = await params
  if (!TOKEN_RE.test(token)) return notFound()

  const loaded = await load(token)
  if (!loaded) return notFound()
  const { supabase, proposal, items } = loaded

  // The first open is worth knowing about; later ones are not.
  if (proposal.status === 'sent' && !proposal.viewed_at) {
    const now = new Date().toISOString()
    await supabase.from('proposals').update({ status: 'viewed', viewed_at: now }).eq('id', proposal.id)
    await supabase.from('activities').insert({
      organization_id: proposal.organization_id,
      contact_id: proposal.contact_id ?? null,
      type: 'note',
      title: `Proposal ${proposal.proposal_number} opened`,
      description: `${proposal.title}`,
      status: 'completed',
      completed_at: now,
      metadata: { proposal_id: proposal.id },
    })
  }

  const banner =
    proposal.status === 'accepted'
      ? { tone: 'success' as const, text: `Approved${proposal.accepted_by_name ? ` by ${proposal.accepted_by_name}` : ''}. Thank you. We have started sourcing and will confirm your ship date in writing.` }
      : proposal.status === 'declined'
        ? { tone: 'muted' as const, text: 'You let us know this one is not going ahead. If that changes, reply to our email and we will pick it straight back up.' }
        : undefined

  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? ''
  const html = renderProposalHtml(proposal, items, { acceptAction: `${basePath}/p/${token}`, banner })
  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Robots-Tag': 'noindex, nofollow',
      'Referrer-Policy': 'no-referrer',
    },
  })
}

export async function POST(request: Request, { params }: { params: Promise<{ token: string }> }) {
  const { token } = await params
  if (!TOKEN_RE.test(token)) return notFound()

  const loaded = await load(token)
  if (!loaded) return notFound()
  const { supabase, proposal } = loaded

  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? ''
  const back = NextResponse.redirect(new URL(`${basePath}/p/${token}`, request.url), 303)

  // Already decided: a second submission changes nothing.
  if (proposal.status === 'accepted' || proposal.status === 'declined') return back

  const form = await request.formData().catch(() => null)
  const decision = String(form?.get('decision') ?? '')
  const name = String(form?.get('name') ?? '').trim().slice(0, 200)
  const note = String(form?.get('note') ?? '').trim().slice(0, 2000)
  if (decision !== 'accept' && decision !== 'decline') return back

  const now = new Date().toISOString()
  const accepted = decision === 'accept'

  await supabase
    .from('proposals')
    .update({
      status: accepted ? 'accepted' : 'declined',
      accepted_at: accepted ? now : null,
      declined_at: accepted ? null : now,
      accepted_by_name: name || null,
      accepted_note: note || null,
    })
    .eq('id', proposal.id)

  if (proposal.client_occasion_id) {
    await supabase
      .from('client_occasions')
      .update({ status: accepted ? 'approved' : 'planned' })
      .eq('id', proposal.client_occasion_id)
  }

  await supabase.from('activities').insert({
    organization_id: proposal.organization_id,
    contact_id: proposal.contact_id ?? null,
    deal_id: proposal.deal_id ?? null,
    type: 'note',
    title: `Proposal ${proposal.proposal_number} ${accepted ? 'APPROVED' : 'declined'}${name ? ` by ${name}` : ''}`,
    description: [proposal.title, note ? `Their note: ${note}` : null].filter(Boolean).join('\n'),
    status: 'completed',
    completed_at: now,
    metadata: { proposal_id: proposal.id, decision, note, by: name },
  })

  // Someone needs to act on an approval the same day.
  if (accepted) {
    await supabase.from('activities').insert({
      organization_id: proposal.organization_id,
      contact_id: proposal.contact_id ?? null,
      deal_id: proposal.deal_id ?? null,
      type: 'task',
      title: `Start sourcing: ${proposal.title}`,
      description: `${proposal.proposal_number} approved${name ? ` by ${name}` : ''}. Confirm the ship date in writing, take payment, and lock the recipient list.`,
      status: 'pending',
      due_date: now,
      metadata: { priority: 'urgent', task_status: 'todo', proposal_id: proposal.id },
    })
  }

  return back
}

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
